name: Formatter

on:
  push:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format code
        run: make format
